# Generated by Django 3.2 on 2021-04-15 00:49

from django.db import migrations, models
import django.db.models.deletion
import hello_world.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artikal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('kolicina', models.PositiveIntegerField()),
                ('cijena_pojedinog', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('godina_proizvodnje', models.PositiveIntegerField(default=hello_world.util.current_year)),
            ],
        ),
        migrations.CreateModel(
            name='Vlasnik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=255)),
                ('prezime', models.CharField(max_length=255)),
                ('automobili', models.ManyToManyField(to='hello_world.Auto')),
            ],
        ),
        migrations.CreateModel(
            name='AutoZaProdaju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artikal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.artikal')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.auto')),
            ],
        ),
        migrations.CreateModel(
            name='AutomobilskiDio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.CharField(max_length=255)),
                ('artikal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.artikal')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello_world.auto')),
            ],
        ),
    ]
